Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2024-11, with the labels that each got.

#98 docs: minor edits requested by PM
  src/content/docs/discovery/architecture.mdx
Labels: documentation

#69 USF-1325: Checkout dropin install/init
  astro.config.mjs
  public/images/pdp/pdp-installation.png
  src/content/docs/dropins/checkout/checkout-installation.mdx
Labels: documentation

#102 USF-1325: Checkout initialization
  astro.config.mjs
  src/content/docs/dropins/checkout/checkout-initialization.mdx
  src/content/docs/dropins/checkout/checkout-installation.mdx
Labels: documentation

#99 Add user account functions
  astro.config.mjs
  src/content/docs/dropins/user-account/functions.mdx
Labels: documentation

#101 fix: remove errant quote breaking launch script
  astro.config.mjs
Labels: bug

#100 Updates to launch checklist based on feedback
  public/images/implementation/iterative-rollout-source.drawio.drawio
  public/images/implementation/iterative-rollout-v1.svg
  src/components/Checklist.astro
  src/components/tutorial/ProgressStore.ts
  src/content/docs/discovery/index.mdx
  src/content/docs/launch/index.mdx
Labels: documentation, enhancement

#106 USF-1686: Add footer copyright / links for legal
  astro.config.mjs
  pnpm-lock.yaml
  src/components/FooterLinks.astro
  src/components/overrides/Footer.astro
  src/utils/i18n.ts
Labels: enhancement

#71 USF-1327: Checkout containers (redux)
  astro.config.mjs
  src/content/docs/dropins/checkout/checkout-containers.mdx
  src/content/docs/dropins/checkout/containers/bill-to-shipping-address.mdx
  src/content/docs/dropins/checkout/containers/estimate-shipping.mdx
  src/content/docs/dropins/checkout/containers/login-form.mdx
  src/content/docs/dropins/checkout/containers/merged-cart-banner.mdx
  src/content/docs/dropins/checkout/containers/order-confirmation-header.mdx
  src/content/docs/dropins/checkout/containers/out-of-stock.mdx
  src/content/docs/dropins/checkout/containers/payment-methods.mdx
  src/content/docs/dropins/checkout/containers/place-order.mdx
  src/content/docs/dropins/checkout/containers/server-error.mdx
  src/content/docs/dropins/checkout/containers/shipping-methods.mdx
  src/content/docs/dropins/checkout/functions.mdx
  src/content/docs/dropins/checkout/initialization.mdx
  src/content/docs/dropins/checkout/installation.mdx
  src/content/docs/dropins/checkout/slots.mdx
  src/content/docs/dropins/checkout/styles.mdx
Labels: documentation

#104 Add User Account dropin docs
  astro.config.mjs
  public/images/dropins/user-account/address-form-container.png
  public/images/dropins/user-account/address-form-one-column.png
  public/images/dropins/user-account/address-form-two-column.png
  public/images/dropins/user-account/addresses-full-all.png
  public/images/dropins/user-account/addresses-full-edit.png
  public/images/dropins/user-account/addresses-full-empty.png
  public/images/dropins/user-account/addresses-minified-empty.png
  public/images/dropins/user-account/addresses-minified-multiple.png
  public/images/dropins/user-account/addresses-selectable-new-address.png
  public/images/dropins/user-account/addresses-selectable-selected.png
  public/images/dropins/user-account/customer-info-change-password.png
  public/images/dropins/user-account/customer-info-default.png
  public/images/dropins/user-account/customer-info-edit-with-password.png
  public/images/dropins/user-account/customer-info-edit.png
  public/images/dropins/user-account/find-styles-user-account.png
  public/images/dropins/user-account/initial-form-layout.png
  public/images/dropins/user-account/mixed-layout.png
  public/images/dropins/user-account/orders-full-all.png
  public/images/dropins/user-account/orders-full-no-orders.png
  public/images/dropins/user-account/orders-minified-multiple.png
  public/images/dropins/user-account/orders-minified-none.png
  public/images/dropins/user-account/sidebar-overview.png
  public/images/dropins/user-account/sidebar1.png
  public/images/dropins/user-account/sidebar2.png
  public/images/dropins/user-account/three-column-layout.png
  public/images/dropins/user-account/two-column-layout.png
  src/content/docs/dropins/user-account/containers/address-form.mdx
  src/content/docs/dropins/user-account/containers/addresses.mdx
  src/content/docs/dropins/user-account/containers/customer-information.mdx
  src/content/docs/dropins/user-account/containers/orders-list.mdx
  src/content/docs/dropins/user-account/files/AccountLoaders.css
  src/content/docs/dropins/user-account/files/AddressActions.css
  src/content/docs/dropins/user-account/files/AddressCard.css
  src/content/docs/dropins/user-account/files/AddressFormWrapper.css
  src/content/docs/dropins/user-account/files/AddressModal.css
  src/content/docs/dropins/user-account/files/AddressesWrapper.css
  src/content/docs/dropins/user-account/files/ChangePassword.css
  src/content/docs/dropins/user-account/files/CustomerInformationCard.css
  src/content/docs/dropins/user-account/files/EditCustomerInformation.css
  src/content/docs/dropins/user-account/files/EmptyList.css
  src/content/docs/dropins/user-account/files/Form.css
  src/content/docs/dropins/user-account/files/OrdersListAction.css
  src/content/docs/dropins/user-account/files/OrdersListCard.css
  src/content/docs/dropins/user-account/files/OrdersListWrapper.css
  src/content/docs/dropins/user-account/functions.mdx
  src/content/docs/dropins/user-account/initialization.mdx
  src/content/docs/dropins/user-account/sidebar.mdx
  src/content/docs/dropins/user-account/slots.mdx
  src/content/docs/dropins/user-account/styles.mdx
  src/content/docs/dropins/user-account/tutorials.mdx
Labels: documentation

#103 USF-1323: Checkout dropin
  astro.config.mjs
  public/images/dropins/findstylescheckout.png
  public/images/pdp/pdp-installation.png
  src/components/OptionsTable.astro
  src/content/docs/dropins/checkout/checkout-containers.mdx
  src/content/docs/dropins/checkout/checkout-functions.mdx
  src/content/docs/dropins/checkout/checkout-installation.mdx
  src/content/docs/dropins/checkout/checkout-slots.mdx
  src/content/docs/dropins/checkout/checkout-styles.mdx
  src/content/docs/dropins/checkout/containers/bill-to-shipping-address.mdx
  src/content/docs/dropins/checkout/containers/estimate-shipping.mdx
  src/content/docs/dropins/checkout/containers/login-form.mdx
  src/content/docs/dropins/checkout/containers/merged-cart-banner.mdx
  src/content/docs/dropins/checkout/containers/order-confirmation-header.mdx
  src/content/docs/dropins/checkout/containers/out-of-stock.mdx
  src/content/docs/dropins/checkout/containers/payment-methods.mdx
  src/content/docs/dropins/checkout/containers/place-order.mdx
  src/content/docs/dropins/checkout/containers/server-error.mdx
  src/content/docs/dropins/checkout/containers/shipping-methods.mdx
  src/content/docs/dropins/checkout/files/BillToShippingAddress.css
  src/content/docs/dropins/checkout/files/EstimateShipping.css
  src/content/docs/dropins/checkout/files/Heading.css
  src/content/docs/dropins/checkout/files/LoginForm.css
  src/content/docs/dropins/checkout/files/OrderConfirmationHeader.css
  src/content/docs/dropins/checkout/files/OutOfStock.css
  src/content/docs/dropins/checkout/files/OverlayLoader.css
  src/content/docs/dropins/checkout/files/PaymentMethods.css
  src/content/docs/dropins/checkout/files/PlaceOrder.css
  src/content/docs/dropins/checkout/files/ServerError.css
  src/content/docs/dropins/checkout/files/ShippingMethods.css
  src/content/docs/dropins/checkout/functions.mdx
  src/content/docs/dropins/checkout/index.mdx
  src/content/docs/dropins/checkout/initialization.mdx
  src/content/docs/dropins/checkout/installation.mdx
  src/content/docs/dropins/checkout/slots.mdx
  src/content/docs/dropins/checkout/styles.mdx
  src/styles/custom.css
Labels: documentation

#109 Add CodeInclude component
  src/components/CodeInclude.astro
Labels: enhancement

#111 Update package dependencies
  package.json
  pnpm-lock.yaml
  src/components/FooterLinks.astro
  src/components/overrides/PageFrame.astro
  src/components/overrides/Pagination.astro
  src/pages/playgrounds/index.astro
Labels: dependencies

#115 SCP beta 24 updates
  src/content/docs/setup/storefront-compatibility.mdx
Labels: documentation

#108 docs: refresh landing page w/ new content
  src/content/docs/index.mdx
Labels: documentation

#88 Cart functions
  src/components/CodeInclude.astro
  src/content/docs/dropins/cart/_includes/cartModel.ts
  src/content/docs/dropins/cart/cart-functions.mdx
  src/content/docs/dropins/cart/index.mdx
Labels: documentation

#107 USF-1328: Checkout slots
  astro.config.mjs
  src/content/docs/dropins/checkout/slots.mdx
Labels: documentation

#117 docs: minor editorial updates
  astro.config.mjs
  src/content/docs/index.mdx
Labels: documentation

#118 Small edits to checkout initialization topic
  src/content/docs/dropins/checkout/initialization.mdx
Labels: documentation

#116 Add cart initialization doc
  astro.config.mjs
  src/content/docs/dropins/cart/initialization.mdx
Labels: documentation

#123 Checkout tutorial: BOPIS
  astro.config.mjs
  public/images/dropins/checkout/bopis-content-fragment.png
  public/images/dropins/checkout/bopis-render-pickup-locations.png
  public/images/dropins/checkout/bopis-toggle-buttons.png
  src/content/docs/dropins/checkout/tutorials/buy-online-pickup-in-store.mdx
Labels: documentation

#128 Order summary line
  astro.config.mjs
  public/images/dropins/cart/order-summary-line.png
  src/content/docs/dropins/cart/containers/order-summary-line.mdx
Labels: documentation

#110 Update cart container docs
  astro.config.mjs
  public/images/dropins/cart/apply-coupon.png
  public/images/dropins/cart/cart-container.png
  public/images/dropins/cart/cart-summary-grid-small.png
  public/images/dropins/cart/cart-summary-list.png
  public/images/dropins/cart/empty-cart.png
  public/images/dropins/cart/estimate-shipping.png
  public/images/dropins/cart/mini-cart.png
  public/images/dropins/cart/order-summary-line.png
  public/images/dropins/cart/order-summary.png
  src/components/OptionsTable.astro
  src/content/docs/dropins/cart/containers/cart-summary-grid.mdx
  src/content/docs/dropins/cart/containers/cart-summary-list.mdx
  src/content/docs/dropins/cart/containers/cart.mdx
  src/content/docs/dropins/cart/containers/coupons.mdx
  src/content/docs/dropins/cart/containers/empty-cart.mdx
  src/content/docs/dropins/cart/containers/estimate-shipping.mdx
  src/content/docs/dropins/cart/containers/minicart.mdx
  src/content/docs/dropins/cart/containers/order-summary-line.mdx
  src/content/docs/dropins/cart/containers/order-summary.mdx
  src/content/docs/dropins/cart/index.mdx
  src/content/docs/dropins/checkout/containers/estimate-shipping.mdx
Labels: documentation
