Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2024-09, with the labels that each got.

#42 USF-1052: Cart feature matrix
  src/content/docs/dropins/cart/index.mdx
Labels: documentation

#43 USF-1440: Checkout feature matrix
  astro.config.mjs
  src/content/docs/dropins/checkout/index.mdx
Labels: documentation

#44 USF-1442: User account feature matrix
  src/content/docs/dropins/user-account/index.mdx
  src/content/docs/dropins/user-auth/index.mdx
Labels: documentation

#45 Feature matrices for dropins
  astro.config.mjs
  src/content/docs/dropins/cart/index.mdx
  src/content/docs/dropins/checkout/index.mdx
  src/content/docs/dropins/user-account/index.mdx
  src/content/docs/dropins/user-auth/index.mdx
  src/styles/badge.css
  src/styles/custom.css
Labels: documentation

#46 fix: apply consistent styling to badges
  src/styles/badge.css
Labels: bug

#47 fix: resolve link validation errors in LinkCard component
  src/components/LinkCard.astro
  src/content/docs/index.mdx
Labels: bug

#37 USF-1474: Add Storefront Compatibility package doc
  src/content/docs/get-started/requirements.mdx
  src/content/docs/get-started/storefront-compatibility.mdx
Labels: documentation

#48 DATA-5753: PDP use cases
  src/content/docs/dropins/product-details/files/zoom.css
  src/content/docs/dropins/product-details/index.mdx
  src/content/docs/dropins/product-details/pdp-containers.mdx
  src/content/docs/dropins/product-details/pdp-functions.mdx
  src/content/docs/dropins/product-details/pdp-styles.mdx
Labels: documentation

#50 Revert "USF-1474: Add Storefront Compatibility package doc"
  src/content/docs/get-started/requirements.mdx
  src/content/docs/get-started/storefront-compatibility.mdx
Labels: documentation

#51 Replace boilerplate fork repo with upstream repo
  src/content/docs/get-started/index.mdx
Labels: documentation

#41 Template structure
  _drafts/ShowSelectedPage.astro
  _drafts/_dropins.mdx
  _drafts/config.json
  _drafts/functions.mdx
  _drafts/oldIntroText.mdx
  _drafts/scraps.txt
  _drafts/slots.js
  _drafts/slots.mdx
  _drafts/test.css
  _dropin-templates/SidebarConfiguration.mjs
  _dropin-templates/dropin-anatomy.mdx
  _dropin-templates/dropin-containers.mdx
  _dropin-templates/dropin-data-events.mdx
  _dropin-templates/dropin-functions.mdx
  _dropin-templates/dropin-initialization.mdx
  _dropin-templates/dropin-labels.mdx
  _dropin-templates/dropin-overview.mdx
  _dropin-templates/dropin-prerequisites.mdx
  _dropin-templates/dropin-slots.mdx
  _dropin-templates/dropin-styles.mdx
  astro.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/Graphiql/GraphiQLEditor.jsx
  src/components/LinkCard.astro
  src/content/docs/dropins/all/anatomy.mdx
  src/content/docs/dropins/all/branding.mdx
  src/content/docs/dropins/all/enriching.mdx
  src/content/docs/dropins/all/eventbus.mdx
  src/content/docs/dropins/all/extending.mdx
  src/content/docs/dropins/all/installing.mdx
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/dropins/all/localizing.mdx
  src/content/docs/dropins/all/styling.mdx
  src/content/docs/dropins/checkout/index.mdx
  src/content/docs/dropins/index.mdx
  src/content/docs/dropins/product-details/pdp-slots.mdx
  src/content/docs/index.mdx
  src/pages/playgrounds/commerce-boilerplate.astro
  src/pages/playgrounds/commerce-services.astro
  src/pages/playgrounds/index.astro
  src/pages/videos/customize-cart.astro
  src/pages/videos/customize-checkout.astro
  src/pages/videos/customize-pdp.astro
  src/pages/videos/index.astro
  src/styles/colors.css
  src/styles/layout.css
  src/styles/text.css
  tsconfig.json
Labels: documentation

#55 fix: change badges for dropins to Ready for VIPs
  astro.config.mjs
  pnpm-lock.yaml
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/dropins/cart/index.mdx
  src/content/docs/dropins/index.mdx
  src/content/docs/index.mdx
  src/styles/badge.css
  src/styles/colors.css
Labels: enhancement, editorial

#57 Update dropin badges to "Ready to Implement"
  src/content/docs/dropins/all/introduction.mdx
Labels: maintenance, editorial

#58 chore: update launch script for analytics
  astro.config.mjs
Labels: maintenance

#60 USF 1509 - Cart Summary supports configuration
  src/content/docs/dropins/cart/cart-containers.mdx
Labels: documentation

#62 fix: LinkCard component takes link; not href
  src/content/docs/get-started/index.mdx
  src/content/docs/get-started/run-lighthouse.mdx
Labels: bug

#63 fix: redirect orphaned pages
  astro.config.mjs
Labels: bug

#64 USF-1326: Added initial draft of checkout styles
  astro.config.mjs
  pnpm-lock.yaml
  public/images/dropins/findstylescheckout.png
  src/content/docs/dropins/checkout/checkout-styles.mdx
  src/content/docs/dropins/checkout/files/AddressForm.css
  src/content/docs/dropins/checkout/files/BillToShippingAddress.css
  src/content/docs/dropins/checkout/files/EstimateShipping.css
  src/content/docs/dropins/checkout/files/FieldsForm.css
  src/content/docs/dropins/checkout/files/Heading.css
  src/content/docs/dropins/checkout/files/LoginForm.css
  src/content/docs/dropins/checkout/files/OutOfStock.css
  src/content/docs/dropins/checkout/files/OverlayLoader.css
  src/content/docs/dropins/checkout/files/PaymentMethods.css
  src/content/docs/dropins/checkout/files/PlaceOrder.css
  src/content/docs/dropins/checkout/files/ServerError.css
  src/content/docs/dropins/checkout/files/ShippingMethods.css
  src/styles/custom.css
Labels: documentation

#65 docs: align PDP overview with template
  src/content/docs/dropins/product-details/index.mdx
Labels: documentation

#59 USF-1510: Cart Summary has a Footer Slot
  src/content/docs/dropins/cart/cart-slots.mdx
Labels: documentation

#66 Revert "USF 1509 - Cart Summary supports configuration"
  src/content/docs/dropins/cart/cart-containers.mdx
Labels: documentation

#67 docs: rewrite generic dropin install
  src/content/docs/dropins/all/branding.mdx
  src/content/docs/dropins/all/extending.mdx
  src/content/docs/dropins/all/installing.mdx
Labels: documentation

#68 USF-1329: Checkout dropin functions
  astro.config.mjs
  src/components/OptionsTable.astro
  src/content/docs/dropins/checkout/checkout-functions.mdx
  src/styles/custom.css
Labels: documentation
