Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2024-12, with the labels that each got.

#136 Add order styles file
  src/content/docs/dropins/order/files/customer-details-content.css
  src/content/docs/dropins/order/files/empty-list.css
  src/content/docs/dropins/order/files/order-actions.css
  src/content/docs/dropins/order/files/order-cancel.css
  src/content/docs/dropins/order/files/order-cost-summary-content.css
  src/content/docs/dropins/order/files/order-loaders.css
  src/content/docs/dropins/order/files/order-product-list-content.css
  src/content/docs/dropins/order/files/order-search-form.css
  src/content/docs/dropins/order/files/order-status-content.css
  src/content/docs/dropins/order/files/return-order-message.css
  src/content/docs/dropins/order/files/return-order-product-list.css
  src/content/docs/dropins/order/files/return-reason-form.css
  src/content/docs/dropins/order/files/returns-list-content.css
  src/content/docs/dropins/order/files/shipping-status-card.css
  src/content/docs/dropins/order/styles.mdx
Labels: documentation

#138 Fix TOC and delete Cart container
  astro.config.mjs
  src/content/docs/dropins/cart/containers/cart.mdx
  src/content/docs/dropins/cart/index.mdx
Labels: documentation

#121 USF-894: Add payment method (Braintree)
  astro.config.mjs
  src/content/docs/dropins/checkout/slots.mdx
  src/content/docs/dropins/checkout/tutorials/add-payment-method.mdx
Labels: documentation

#139 Tutorial config cart summary
  astro.config.mjs
  public/images/dropins/cart/cart-summary-dropdown.png
  public/images/dropins/cart/cart-summary-percentage.png
  public/images/dropins/cart/cart-summary-stepper.png
  public/images/dropins/cart/cart-summary-total.png
  public/images/dropins/cart/cart-table.png
  src/content/docs/dropins/cart/tutorials/configure-cart-summary.mdx
Labels: documentation

#127 docs: update initializers config
  src/content/docs/dropins/checkout/initialization.mdx
  src/content/docs/dropins/product-details/initialization.mdx
Labels: documentation

#125 Cart slots
  src/content/docs/dropins/cart/index.mdx
  src/content/docs/dropins/cart/slots.mdx
Labels: documentation

#140 Extending product lines in the cart tutorial
  astro.config.mjs
  public/images/dropins/cart/cart-product-line-final.png
  public/images/dropins/cart/cart-product-line-footer.png
  public/images/dropins/cart/cart-product-line-shipping.png
  src/content/docs/dropins/cart/tutorials/add-product-lines-to-cart-summary.mdx
  src/content/docs/dropins/cart/tutorials/configure-cart-summary.mdx
Labels: documentation

#143 USF-1787: PDP containers
  astro.config.mjs
  src/content/docs/dropins/product-details/containers/product-attributes.mdx
  src/content/docs/dropins/product-details/containers/product-description.mdx
  src/content/docs/dropins/product-details/containers/product-details.mdx
  src/content/docs/dropins/product-details/containers/product-gallery.mdx
  src/content/docs/dropins/product-details/containers/product-header.mdx
  src/content/docs/dropins/product-details/containers/product-options.mdx
  src/content/docs/dropins/product-details/containers/product-price.mdx
  src/content/docs/dropins/product-details/containers/product-quantity.mdx
  src/content/docs/dropins/product-details/containers/product-short-description.mdx
  src/content/docs/dropins/product-details/installation.mdx
Labels: documentation

#130 Checkout tutorial: multi-step
  astro.config.mjs
  public/images/dropins/checkout/continue-to-payment.png
  public/images/dropins/checkout/continue-to-shipping.png
  public/images/dropins/checkout/empty-cart.png
  public/images/dropins/checkout/order-confirmation.png
  public/images/dropins/checkout/render-containers-no-styles.png
  public/images/dropins/checkout/render-containers-with-styles.png
  src/content/docs/dropins/checkout/tutorials/multi-step.mdx
Labels: documentation

#144 Add overview for order drop-in
  astro.config.mjs
  public/images/dropins/order/order-details-containers.png
  public/images/dropins/order/return-details-containers.png
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/dropins/order/index.mdx
Labels: documentation

#142 USF-921: How to Enrich drop-ins
  astro.config.mjs
  public/images/AddContent.png
  public/images/AddEnrichmentBlock.png
  public/images/ContentEnrichment.svg
  public/images/EnrichmentContent.png
  public/images/PositionContentBlock.png
  src/components/Link.astro
  src/content/docs/dropins/all/enriching.mdx
  src/content/docs/resources/index.mdx
Labels: documentation

#145 Order drop-in slots
  astro.config.mjs
  src/content/docs/dropins/order/slots.mdx
Labels: documentation

#147 SCP-beta29
  src/content/docs/setup/storefront-compatibility.mdx
Labels: documentation

#119 Update supported feature matrices
  src/content/docs/dropins/cart/index.mdx
  src/content/docs/dropins/checkout/index.mdx
  src/content/docs/dropins/order/index.mdx
  src/content/docs/dropins/user-account/index.mdx
Labels: documentation

#141 Create compatibility_table
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/get-started/release.mdx
Labels: documentation

#148 USF-1848
  astro.config.mjs
  eslint.config.cjs
  package.json
  pnpm-lock.yaml
  public/images/PrexBlock.png
  public/images/ProductDetailsLayout.png
  src/content/docs/dropins/all/extending.mdx
  src/content/docs/dropins/all/layouts.mdx
  tailwind.config.cjs
  tailwind.config.js
Labels: documentation

#150 USF-922: Add third-party components to drop-in
  pnpm-lock.yaml
  src/content/docs/dropins/all/extending.mdx
Labels: documentation

#153 Compatibility table updates
  src/content/docs/get-started/release.mdx
  src/styles/custom.css
Labels: documentation, enhancement

#152 USF-922: Extending drop-ins with Commerce APIs
  astro.config.mjs
  src/content/docs/dropins/all/enriching.mdx
  src/content/docs/dropins/all/extending.mdx
  src/content/docs/dropins/all/slots.mdx
Labels: documentation

#154 USF-1136 Docs for creating experiments
  _drafts/_experiments.mdx
  astro.config.mjs
  public/images/ExperimentOne.png
  public/images/MetadataExperiment.png
  public/images/PlaceholderChanges.png
  src/content/docs/dropins/all/enriching.mdx
  src/content/docs/dropins/all/experimenting.mdx
Labels: documentation

#146 fix: broken links for http
  src/components/OptionsTable.astro
  src/content/docs/get-started/storefront-structure.mdx
Labels: bug

#156 fix: correct find-replace typos of dropin-in
  _dropin-templates/SidebarConfiguration.mjs
  _dropin-templates/dropin-labels.mdx
  _dropin-templates/dropin-prerequisites.mdx
  src/content/docs/discovery/data-export-validation.mdx
  src/content/docs/discovery/luma-bridge.mdx
  src/content/docs/dropins/all/branding.mdx
  src/content/docs/dropins/all/eventbus.mdx
  src/content/docs/dropins/all/extending.mdx
  src/content/docs/dropins/all/installing.mdx
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/dropins/all/slots.mdx
  src/content/docs/dropins/all/styling.mdx
  src/content/docs/dropins/cart/installation.mdx
  src/content/docs/dropins/cart/styles.mdx
  src/content/docs/dropins/order/files/return-order-product-list.css
  src/content/docs/dropins/order/files/return-reason-form.css
  src/content/docs/dropins/order/styles.mdx
  src/content/docs/dropins/product-details/installation.mdx
  src/content/docs/dropins/product-details/styles.mdx
  src/content/docs/dropins/user-account/initialization.mdx
  src/content/docs/dropins/user-auth/auth-functions.mdx
  src/content/docs/get-started/_storefront-blocks.mdx
  src/content/docs/get-started/index.mdx
  src/content/docs/get-started/storefront-structure.mdx
  src/content/docs/seo/indexing.mdx
  src/content/docs/troubleshooting/faq.mdx
  src/content/docs/troubleshooting/pagespeed-issues.mdx
  src/content/integrations/integrate-react.mdx
  src/content/integrations/integrate-vue.mdx
  src/content/integrations/overview.mdx
  src/pages/playgrounds/index.astro
  src/pages/videos/customize-pdp.astro
  src/pages/videos/index.astro
Labels: editorial
