Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2025-03, with the labels that each got.

#202 fix: add redirects for route changes fix api-playground
  astro.config.mjs
  package.json
  pnpm-lock.yaml
Labels: documentation, maintenance, dependencies

#210 USF-2007 - UpdateProductsFromCart Docs
  src/content/docs/dropins/cart/functions.mdx
Labels: documentation

#215 Add creating drop-in topic
  astro.config.mjs
  pnpm-lock.yaml
  src/content/docs/dropins/all/creating.mdx
Labels: documentation

#220 feat: improved launch checklist
  src/components/Checklist.astro
  src/components/tutorial/ProgressStore.ts
  src/content/docs/storefront-setup/launch/index.mdx
Labels: enhancement

#217 GiftOptions tutorial
  astro.config.mjs
  public/images/dropins/cart/pdp-gift-options-cart.png
  public/images/dropins/cart/pdp-gift-options-default.png
  public/images/dropins/cart/pdp-gift-options-selected.png
  src/content/docs/dropins/cart/tutorials/gift-options.mdx
Labels: documentation

#223 fix: remove redundancy from file paths/URLs & add redirects
  astro.config.mjs
  src/content/docs/dropins/product-details/index.mdx
  src/content/docs/get-started/boilerplate-project.mdx
  src/content/docs/get-started/index.mdx
  src/content/docs/setup/analytics/instrumentation.mdx
  src/content/docs/setup/configuration/commerce-configuration.mdx
  src/content/docs/setup/configuration/content-delivery-network.mdx
  src/content/docs/setup/configuration/gated-content.mdx
  src/content/docs/setup/configuration/index.mdx
  src/content/docs/setup/configuration/storefront-compatibility.mdx
  src/content/docs/setup/discovery/architecture.mdx
  src/content/docs/setup/discovery/data-export-validation.mdx
  src/content/docs/setup/discovery/luma-bridge.mdx
  src/content/docs/setup/index.mdx
  src/content/docs/setup/launch/index.mdx
  src/content/docs/setup/seo/indexing.mdx
  src/content/docs/setup/seo/metadata.mdx
Labels: maintenance

#224 fix: revert custom table style
  src/styles/custom.css
Labels: maintenance

#225 fix: terminal warnings
  src/components/Graphiql/GraphiQLEditor.jsx
  src/content/docs/merchants/get-started/terms-and-conditions.mdx
Labels: maintenance

#226 fix: embed component
  src/components/Embed.astro
Labels: bug

#221 Placeholders Experimentation
  package-lock.json
  public/images/PlaceholderExperiment.png
  public/images/PlaceholderOverrides.png
  public/images/PlaceholderPreviewExperiment.png
  src/content/docs/merchants/get-started/experiments.mdx
Labels: documentation

#228 Fix pnpm on CI
  .jenkins/deliver-build.groovy
Labels: dependencies

#229 Fix: Ensure Google Drive files convert correctly during upload
  src/content/docs/get-started/index.mdx
Labels: documentation

#233 Fixes layout of API playground
  src/components/Graphiql/graphiql-overrides.css
  src/content/docs/playgrounds/commerce-services.mdx
Labels: bug, maintenance
