Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2025-06, with the labels that each got.

#309 CCSAAS-2095: Storefront badging (initial)
  src/components/overrides/Badge.astro
  src/content/docs/dropins/cart/index.mdx
  src/content/docs/dropins/checkout/index.mdx
  src/content/docs/dropins/order/index.mdx
  src/content/docs/dropins/product-details/index.mdx
  src/content/docs/dropins/user-account/index.mdx
  src/content/docs/dropins/user-auth/index.mdx
  src/content/docs/setup/configuration/content-delivery-network.mdx
  src/content/docs/setup/configuration/storefront-compatibility/install.mdx
  src/content/docs/setup/discovery/luma-bridge.mdx
Labels: enhancement

#304 LYNX-879 Documentation update for SCP-4.8.3 and SCP-4.7.5 releases
  src/content/docs/releases/changelog.mdx
  src/content/docs/setup/configuration/storefront-compatibility/v247.mdx
  src/content/docs/setup/configuration/storefront-compatibility/v248.mdx
Labels: documentation

#310 fix: broken links
  src/content/docs/releases/index.mdx
  src/content/docs/setup/configuration/storefront-compatibility/v247.mdx
  src/content/docs/setup/configuration/storefront-compatibility/v248.mdx
Labels: bug

#314 fix: page title spacing on mobile
  src/components/overrides/PageTitle.astro
Labels: bug

#318 feat: add examples and README instructions for content imports
  .vscode/settings.json
  README.md
  pnpm-lock.yaml
  src/content/fragments/example-fragment.mdx
Labels: documentation, enhancement

#322 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#311 Fix the Audit Web Vitals GH workflow
  .github/workflows/lighthouseci.yml
  .gitignore
  .lighthouserc.cjs
  astro.config.mjs
  package.json
Labels: bug, maintenance

#335 migrated tools - updates doc refs
  src/content/docs/get-started/index.mdx
Labels: documentation, maintenance

#337 COMDOX-1256: add redirect for merchant/multistore
  astro.config.mjs
Labels: maintenance

#334 Update Catalog Service links
  src/content/docs/dropins/product-details/index.mdx
  src/content/docs/dropins/product-details/initialization.mdx
  src/content/docs/setup/discovery/data-export-validation.mdx
Labels: maintenance

#348 USF-2308: Workaround for email templates
  public/images/troubleshoot/forgot-password-template-config.png
  public/images/troubleshoot/forgot-password-template.png
  src/content/docs/setup/launch/index.mdx
  src/content/docs/troubleshooting/faq.mdx
Labels: documentation

#347 Wishlist dropin
  astro.config.mjs
  public/images/dropins/wish-list/inspector.png
  public/images/dropins/wish-list/placeholder.webp
  public/images/dropins/wish-list/wishlist-alert.png
  public/images/dropins/wish-list/wishlist-item.png
  public/images/dropins/wish-list/wishlist.png
  src/content/docs/dropins/other/search.mdx
  src/content/docs/dropins/payment-services/index.mdx
  src/content/docs/dropins/payment-services/installation.mdx
  src/content/docs/dropins/product-details/index.mdx
  src/content/docs/dropins/product-details/initialization.mdx
  src/content/docs/dropins/wishlist/containers/container-name.mdx
  src/content/docs/dropins/wishlist/containers/wishlist-alert.mdx
  src/content/docs/dropins/wishlist/containers/wishlist-item.mdx
  src/content/docs/dropins/wishlist/containers/wishlist-toggle.mdx
  src/content/docs/dropins/wishlist/containers/wishlist.mdx
  src/content/docs/dropins/wishlist/files/EmptyWishlist.css
  src/content/docs/dropins/wishlist/files/ImageCarousel.css
  src/content/docs/dropins/wishlist/files/Login.css
  src/content/docs/dropins/wishlist/files/ProductItem.css
  src/content/docs/dropins/wishlist/files/Wishlist.css
  src/content/docs/dropins/wishlist/functions.mdx
  src/content/docs/dropins/wishlist/index.mdx
  src/content/docs/dropins/wishlist/initialization.mdx
  src/content/docs/dropins/wishlist/installation.mdx
  src/content/docs/dropins/wishlist/slots.mdx
  src/content/docs/dropins/wishlist/styles.mdx
  src/content/docs/get-started/boilerplate-project.mdx
  src/content/docs/setup/analytics/instrumentation.mdx
  src/content/docs/setup/configuration/commerce-configuration.mdx
  src/content/docs/setup/discovery/architecture.mdx
  src/content/docs/setup/discovery/data-export-validation.mdx
  src/content/docs/setup/index.mdx
  src/content/docs/troubleshooting/faq.mdx
Labels: documentation

#350 Personalization: copy edits for initial draft (merchant)
  src/content/docs/merchants/get-started/personalization.mdx
Labels: editorial

#330 Personalization
  astro.config.mjs
  public/images/dropins/personalization/targeted-block-fragment.png
  public/images/dropins/personalization/targeted-block-type.png
  public/images/dropins/personalization/targeted-block.png
  src/content/docs/dropins/personalization/containers/targeted-block.mdx
  src/content/docs/dropins/personalization/functions.mdx
  src/content/docs/dropins/personalization/index.mdx
  src/content/docs/dropins/personalization/initialization.mdx
  src/content/docs/merchants/get-started/personalization.mdx
Labels: documentation

#332 WishList dropin
  astro.config.mjs
  public/images/dropins/wish-list/inspector.png
  public/images/dropins/wish-list/wishlist-alert.png
  public/images/dropins/wish-list/wishlist-item.png
  public/images/dropins/wish-list/wishlist.png
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/dropins/wishlist/containers/wishlist-alert.mdx
  src/content/docs/dropins/wishlist/containers/wishlist-item.mdx
  src/content/docs/dropins/wishlist/containers/wishlist-toggle.mdx
  src/content/docs/dropins/wishlist/containers/wishlist.mdx
  src/content/docs/dropins/wishlist/dictionary.mdx
  src/content/docs/dropins/wishlist/files/EmptyWishlist.css
  src/content/docs/dropins/wishlist/files/ImageCarousel.css
  src/content/docs/dropins/wishlist/files/Login.css
  src/content/docs/dropins/wishlist/files/ProductItem.css
  src/content/docs/dropins/wishlist/files/Wishlist.css
  src/content/docs/dropins/wishlist/functions.mdx
  src/content/docs/dropins/wishlist/index.mdx
  src/content/docs/dropins/wishlist/installation.mdx
  src/content/docs/dropins/wishlist/styles.mdx
Labels: documentation

#302 Recommendations
  astro.config.mjs
  public/images/PrexBlock.png
  public/images/PrexBlockNonPDP.png
  public/images/PrexBlockPDP.png
  public/images/dropins/findstylesrecommendations.png
  public/images/dropins/recommendations/product-list.png
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/dropins/all/layouts.mdx
  src/content/docs/dropins/other/recommendations.mdx
  src/content/docs/dropins/recommendations/containers/product-list.mdx
  src/content/docs/dropins/recommendations/dictionary.mdx
  src/content/docs/dropins/recommendations/files/recommendations.css
  src/content/docs/dropins/recommendations/functions.mdx
  src/content/docs/dropins/recommendations/i18n/en_US.json.d.ts
  src/content/docs/dropins/recommendations/index.mdx
  src/content/docs/dropins/recommendations/installation.mdx
  src/content/docs/dropins/recommendations/slots.mdx
  src/content/docs/dropins/recommendations/styles.mdx
  src/content/docs/merchants/get-started/index.mdx
  src/content/docs/merchants/get-started/product-recommendations.mdx
  src/content/docs/setup/discovery/architecture.mdx
Labels: documentation

#357 Add link to personalization on merchant home page
  src/content/docs/merchants/get-started/index.mdx
Labels: editorial

#358 June 2025 release notes
  src/components/changelog/ChangelogEntry.astro
  src/components/changelog/ChangelogFilter.astro
  src/content/docs/releases/changelog.mdx
  src/content/docs/releases/index.mdx
Labels: documentation

#361 Product Discovery: editorial review for initial developer docs
  astro.config.mjs
  src/content/docs/dropins/other/search.mdx
  src/content/docs/dropins/product-discovery/containers/facets.mdx
  src/content/docs/dropins/product-discovery/containers/product-list.mdx
  src/content/docs/dropins/product-discovery/containers/results-info.mdx
  src/content/docs/dropins/product-discovery/containers/search-bar-input.mdx
  src/content/docs/dropins/product-discovery/containers/search-bar-results.mdx
  src/content/docs/dropins/product-discovery/dictionary.mdx
  src/content/docs/dropins/product-discovery/index.mdx
  src/content/docs/dropins/product-discovery/installation.mdx
  src/content/docs/dropins/product-discovery/slots.mdx
  src/content/docs/dropins/user-account/dictionary.mdx
  src/content/docs/releases/changelog.mdx
  src/content/docs/releases/index.mdx
Labels: editorial

#360 Product Discovery Initial documentation
  astro.config.mjs
  package.json
  pnpm-lock.yaml
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/dropins/other/search.mdx
  src/content/docs/dropins/product-discovery/containers/facets.mdx
  src/content/docs/dropins/product-discovery/containers/product-list.mdx
  src/content/docs/dropins/product-discovery/containers/results-info.mdx
  src/content/docs/dropins/product-discovery/containers/search-bar-input.mdx
  src/content/docs/dropins/product-discovery/containers/search-bar-results.mdx
  src/content/docs/dropins/product-discovery/dictionary.mdx
  src/content/docs/dropins/product-discovery/files/facet-list.css
  src/content/docs/dropins/product-discovery/files/facet.css
  src/content/docs/dropins/product-discovery/files/product-item.css
  src/content/docs/dropins/product-discovery/files/product-list.css
  src/content/docs/dropins/product-discovery/files/results-info.css
  src/content/docs/dropins/product-discovery/files/search-alert-message.css
  src/content/docs/dropins/product-discovery/files/search-bar-input.css
  src/content/docs/dropins/product-discovery/files/search-bar-results.css
  src/content/docs/dropins/product-discovery/index.mdx
  src/content/docs/dropins/product-discovery/installation.mdx
  src/content/docs/dropins/product-discovery/slots.mdx
  src/content/docs/dropins/product-discovery/styles.mdx
  src/content/docs/dropins/user-account/dictionary.mdx
  src/content/docs/releases/changelog.mdx
  src/content/docs/releases/index.mdx
Labels: documentation

#355 USF-2169: Multistore developer setup
  astro.config.mjs
  src/content/docs/setup/configuration/multistore-setup.mdx
Labels: documentation

#363 Fix double entry of multistore setup topic
  astro.config.mjs
Labels: maintenance

#366 fix merchant nav link
  astro.config.mjs
Labels: maintenance
