Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2025-04, with the labels that each got.

#230 Use consistent installation and delete extra permissions in Audit Web Vitals workflow
  .github/workflows/lighthouseci.yml
Labels: bug

#240 Add beta badge to SDK section
  astro.config.mjs
Labels: documentation

#238 Multistore — Metadata (Update)
  src/content/docs/merchants/get-started/multistore.mdx
Labels: documentation, editorial

#244 Add SCP 4.7.1 release info
  src/content/docs/setup/configuration/storefront-compatibility.mdx
Labels: documentation

#250 fix: indent format of sidenav
  src/styles/custom.css
Labels: bug

#253 fix: add deprecated tag badge to ProductDetails container
  astro.config.mjs
  src/components/overrides/SidebarSublist.astro
  src/content/docs/dropins/product-details/containers/product-details.mdx
  src/styles/custom.css
  src/styles/layout.css
Labels: maintenance

#252 chore: update packages including astro and starlight
  astro.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/FooterLinks.astro
  src/components/overrides/SocialIcons.astro
Labels: dependencies

#257 fix: remove Textfield component entry in sidenav
  astro.config.mjs
Labels: bug, documentation

#259 add accept-encoding logic for edge origins
  src/content/docs/setup/configuration/content-delivery-network.mdx
Labels: do not merge

#258 fix: improved layout of API playground and site as a whole
  src/components/FullWidthContainer.astro
  src/components/overrides/ContentPanel.astro
  src/components/overrides/Header.astro
  src/components/overrides/PageTitle.astro
  src/components/overrides/SiteTitle.astro
  src/content/docs/playgrounds/commerce-services.mdx
  src/content/docs/videos/add-product-lines-to-cart-summary.mdx
  src/content/docs/videos/buy-online-pickup-in-store.mdx
  src/content/docs/videos/customize-address-form-layout.mdx
  src/content/docs/videos/customize-cart-summary.mdx
  src/content/docs/videos/customize-order-summary-lines.mdx
  src/content/docs/videos/multi-step-checkout.mdx
  src/content/docs/videos/shopper-experience.mdx
  src/styles/custom.css
  src/styles/layout.css
Labels: bug, enhancement

#261 fix: update bullet styles to fix bullets throughout site
  src/components/Diagram.astro
  src/styles/custom.css
Labels: bug

#254 New Checkout Drop-in v1.4.0-beta1
  src/content/docs/dropins/checkout/containers/login-form.mdx
  src/content/docs/dropins/checkout/containers/overview.mdx
  src/content/docs/dropins/checkout/containers/payment-methods.mdx
  src/content/docs/dropins/checkout/containers/shipping-methods.mdx
  src/content/docs/dropins/checkout/containers/terms-and-conditions.mdx
  src/content/docs/merchants/get-started/terms-and-conditions.mdx
  src/content/docs/releases/index.mdx
  src/content/docs/resources/placeholders.mdx
Labels: documentation

#262 fix: update api playground to fix variables section
  src/components/Graphiql/graphiql-overrides.css
  src/components/IFrame.astro
  src/components/overrides/Hero.astro
  src/content/docs/playgrounds/commerce-services.mdx
  src/styles/custom.css
Labels: bug

#264 Fixes CSS styles for lists in Tasks; updates to the GraphiQL editor CSS
  src/components/Graphiql/graphiql-overrides.css
  src/styles/custom.css
Labels: bug

#269 Add cache-busting query param info
  src/content/docs/setup/launch/index.mdx
  src/content/docs/setup/seo/indexing.mdx
Labels: documentation

#265 Add Live Search and Product recommendations notes
  astro.config.mjs
  src/content/docs/dropins/other/recommendations.mdx
  src/content/docs/dropins/other/search.mdx
Labels: documentation

#273 New Checkout Drop-in v1.4.0-beta2
  src/content/docs/dropins/checkout/containers/bill-to-shipping-address.mdx
  src/content/docs/dropins/checkout/containers/login-form.mdx
  src/content/docs/dropins/checkout/containers/merged-cart-banner.mdx
  src/content/docs/dropins/checkout/containers/overview.mdx
  src/content/docs/dropins/checkout/containers/payment-methods.mdx
  src/content/docs/dropins/checkout/containers/place-order.mdx
  src/content/docs/dropins/checkout/containers/shipping-methods.mdx
  src/content/docs/dropins/checkout/slots.mdx
  src/content/docs/releases/index.mdx
Labels: documentation
