Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2025-08, with the labels that each got.

#400 chore: publish SDK release elsie/1.4.0-beta3
  astro.config.mjs
  public/storybook-static/669.d42ffb99.iframe.bundle.js
  public/storybook-static/8684.f76562c5.iframe.bundle.js
  public/storybook-static/docs-API-initializer-mdx.cc34257b.iframe.bundle.js
  public/storybook-static/iframe.html
  public/storybook-static/index.json
  public/storybook-static/main.9dcd66ba.iframe.bundle.js
  public/storybook-static/main.9dcd66ba.iframe.bundle.js.LICENSE.txt
  public/storybook-static/project.json
  public/storybook-static/runtime~main.59f4d668.iframe.bundle.js
Labels: documentation, devops

#408 hotfix: clarify usage of environment parameter
  src/content/docs/setup/analytics/instrumentation.mdx
  src/content/docs/setup/launch/index.mdx
Labels: technical

#409 Documentation update for SCP-4.8.6 and SCP-4.7.9 releases
  src/content/docs/releases/changelog.mdx
  src/content/docs/releases/index.mdx
  src/content/docs/setup/configuration/storefront-compatibility/install.mdx
Labels: technical

#398 Checkout v201 docs
  astro.config.mjs
  src/content/docs/dropins/checkout/index.mdx
  src/content/docs/dropins/checkout/tutorials/add-payment-method.mdx
  src/content/docs/dropins/checkout/tutorials/address-integration.mdx
  src/content/docs/dropins/checkout/tutorials/buy-online-pickup-in-store.mdx
  src/content/docs/dropins/checkout/tutorials/multi-step.mdx
  src/content/docs/releases/changelog.mdx
  src/content/docs/videos/index.mdx
  src/content/docs/videos/multi-step-checkout.mdx
Labels: major-update

#410 Release August 2025 suite
  package.json
  pnpm-lock.yaml
  src/content/docs/dropins/cart/index.mdx
  src/content/docs/releases/changelog.mdx
  src/content/docs/releases/index.mdx
Labels: major-update

#417 Remove test file from mermaid PR
  src/content/docs/resources/product-discovery-diagrams.mdx
Labels: bug

#423 Update diagrams with mermaid
  src/content/docs/dropins/product-discovery/index.mdx
Labels: bug, enhancement

#425 chore: publish SDK release elsie/1.5.0-beta1
  public/storybook-static/8674.299f2f10.iframe.bundle.js
  public/storybook-static/components-InputFile-InputFile-stories.c1fbd587.iframe.bundle.js
  public/storybook-static/components-ProductItemCard-ProductItemCard-stories.032e7d58.iframe.bundle.js
  public/storybook-static/docs-API-event-bus-mdx.437c1c80.iframe.bundle.js
  public/storybook-static/iframe.html
  public/storybook-static/index.json
  public/storybook-static/main.3d1427d4.iframe.bundle.js
  public/storybook-static/main.3d1427d4.iframe.bundle.js.LICENSE.txt
  public/storybook-static/project.json
  public/storybook-static/runtime~main.84d606b7.iframe.bundle.js
Labels: documentation, devops

#432 Enhance product details documentation with scoped contexts support
  src/content/docs/dropins/product-details/containers/product-attributes.mdx
  src/content/docs/dropins/product-details/containers/product-description.mdx
  src/content/docs/dropins/product-details/containers/product-gallery.mdx
  src/content/docs/dropins/product-details/containers/product-header.mdx
  src/content/docs/dropins/product-details/containers/product-options.mdx
  src/content/docs/dropins/product-details/containers/product-price.mdx
  src/content/docs/dropins/product-details/containers/product-quantity.mdx
  src/content/docs/dropins/product-details/containers/product-short-description.mdx
  src/content/docs/dropins/product-details/index.mdx
  src/content/docs/dropins/product-details/initialization.mdx
  src/content/docs/dropins/product-details/installation.mdx
Labels: major-update

#436 fix: json code block
  src/content/docs/setup/analytics/instrumentation.mdx
Labels: bug

#430 Fixed Checkout changelog duplicated entry issue
  src/content/docs/releases/changelog.mdx
Labels: editorial

#442 fixed CodeImport output
  astro.config.mjs
  src/components/CodeInclude.astro
  src/utils/convertDtsToJson.ts
Labels: bug
