Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2025-09, with the labels that each got.

#447 Template updates
  _dropin-templates/dropin-anatomy.mdx
  _dropin-templates/dropin-containers.mdx
  _dropin-templates/dropin-dictionary.mdx
  _dropin-templates/dropin-functions.mdx
  _dropin-templates/dropin-initialization.mdx
  _dropin-templates/dropin-installation.mdx
  _dropin-templates/dropin-labels.mdx
  _dropin-templates/dropin-overview.mdx
  _dropin-templates/dropin-prerequisites.mdx
  _dropin-templates/dropin-slots.mdx
  _dropin-templates/dropin-styles.mdx
Labels: enhancement, major-update

#473 duplicate documentation for create storefront
  src/content/docs/get-started/create-storefront.mdx
  src/content/docs/get-started/index.mdx
Labels: documentation

#453 USF-2773 Integrating the new AddressValidation container in the user-account drop-in
  astro.config.mjs
  public/images/dropins/user-account/address-validation.png
  src/content/docs/dropins/user-account/containers/address-validation.mdx
  src/content/docs/dropins/user-account/tutorials/customize-layout.mdx
  src/content/docs/dropins/user-account/tutorials/validate-address.mdx
Labels: major-update

#476 redirect old link to pdp containers
  astro.config.mjs
Labels: maintenance

#477 add description for compact design in Incrementer
  src/content/docs/sdk/components/incrementer.mdx
Labels: documentation

#420 update metadata references for lowercase sku change
  src/content/docs/setup/seo/indexing.mdx
  src/content/docs/setup/seo/metadata.mdx
Labels: major-update

#482 Adds section for AEM Assets integration in merchant docs
  astro.config.mjs
  src/components/Callouts.astro
  src/components/OptionsTable.astro
  src/content/docs/setup/configuration/aem-assets-configuration.mdx
  src/content/docs/setup/configuration/commerce-configuration.mdx
  src/styles/custom.css
Labels: documentation
