Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2025-02, with the labels that each got.

#182 PAY-5922: Refactor Payment Services payment method codes
  src/content/docs/dropins/checkout/containers/payment-methods.mdx
  src/content/docs/dropins/checkout/containers/place-order.mdx
  src/content/docs/dropins/payment-services/containers/credit-card.mdx
Labels: documentation

#183 USF-1284: Add demo videos
  src/components/LinkCard.astro
  src/pages/videos/add-product-lines-to-cart-summary.astro
  src/pages/videos/buy-online-pickup-in-store.astro
  src/pages/videos/customize-address-form-layout.astro
  src/pages/videos/customize-cart-summary.astro
  src/pages/videos/customize-order-summary-lines.astro
  src/pages/videos/customize-pdp.astro
  src/pages/videos/index.astro
  src/pages/videos/multi-step-checkout.astro
Labels: documentation

#184 Fix: Lock pnpm version to 9.15.4
  .jenkins/deliver-build.groovy
  package.json
Labels: bug

#170 PAY-5859: Payment Services drop-in documentation for Summit
  astro.config.mjs
  src/content/docs/dropins/all/introduction.mdx
  src/content/docs/dropins/checkout/containers/payment-methods.mdx
  src/content/docs/dropins/checkout/containers/place-order.mdx
  src/content/docs/dropins/payment-services/containers/credit-card.mdx
  src/content/docs/dropins/payment-services/dictionary.mdx
  src/content/docs/dropins/payment-services/index.mdx
  src/content/docs/dropins/payment-services/installation.mdx
  src/content/docs/get-started/release.mdx
Labels: documentation, enhancement

#181 USF-1911: Restructured PaymentMethods container with deprecated configs
  src/content/docs/dropins/checkout/containers/payment-methods.mdx
  src/content/docs/dropins/checkout/containers/place-order.mdx
  src/content/docs/get-started/release.mdx
Labels: documentation

#185 Updated Payment Services drop-in version to v1.0.0
  package.json
  pnpm-lock.yaml
Labels: documentation

#187 Updated Payment Services drop-in version to v1.0.1
  package.json
  pnpm-lock.yaml
  src/content/docs/get-started/release.mdx
Labels: documentation

#173 Use v7 sidekick
  src/content/docs/get-started/index.mdx
Labels: documentation

#188 Add PrivacyPolicyConsent slot
  astro.config.mjs
  public/images/user-auth/privacy-policy.png
  src/content/docs/dropins/user-auth/containers/sign-up.mdx
  src/content/docs/dropins/user-auth/slots.mdx
Labels: documentation

#190 fix: citisignal demo url
  src/content/docs/get-started/index.mdx
Labels: documentation

#191 Update checkout supported features table
  src/content/docs/dropins/checkout/index.mdx
Labels: documentation

#192 USF-1975: Synchronize Checkout_PlaceOrder documentation
  package.json
  pnpm-lock.yaml
  src/content/docs/dropins/checkout/containers/place-order.mdx
  src/content/docs/dropins/checkout/tutorials/add-payment-method.mdx
  src/content/docs/dropins/checkout/tutorials/multi-step.mdx
  src/content/docs/get-started/release.mdx
Labels: documentation

#195 Improve the preview-on-pages workflow
  .github/workflows/preview-on-pages.yml
Labels: enhancement, maintenance

#196 feat: add shopper UX video
  src/pages/videos/index.astro
  src/pages/videos/shopper-experience.astro
Labels: documentation

#189 Add docs for mini cart slots
  src/content/docs/dropins/cart/slots.mdx
Labels: documentation

#199 Add links to new queries
  src/content/docs/setup/storefront-compatibility.mdx
Labels: documentation

#198 USF-1934: Rework navigation
  astro.config.mjs
  pnpm-lock.yaml
  public/images/implementation/implementation-overview-v2.svg
  src/components/overrides/Header.astro
  src/content/docs/config/commerce-configuration.mdx
  src/content/docs/config/content-delivery-network.mdx
  src/content/docs/config/index.mdx
  src/content/docs/config/storefront-compatibility.mdx
  src/content/docs/discovery/architecture.mdx
  src/content/docs/discovery/index.mdx
  src/content/docs/launch/index.mdx
  src/content/docs/releases/index.mdx
  src/content/docs/seo/indexing.mdx
  src/content/docs/seo/metadata.mdx
  src/pages/merchants/index.astro
Labels: documentation, maintenance

#197 Add GeoIp section
  src/content/docs/setup/content-delivery-network.mdx
Labels: documentation
