Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2025-05, with the labels that each got.

#278 COMOPT-415: DEVOPS: Developers can access and publish the PREX drop-in
  astro.config.mjs
  src/content/docs/dropins/recommendations/functions.mdx
  src/content/docs/dropins/recommendations/index.mdx
  src/content/docs/dropins/recommendations/installation.mdx
  src/content/docs/dropins/recommendations/slots.mdx
  src/content/docs/dropins/recommendations/styles.mdx
Labels: documentation

#284 Updating as per MSRCH-4606
  src/content/docs/setup/discovery/architecture.mdx
Labels: editorial

#277 USF-2278: initial draft of changes for removing references to gdrive and sharepoint
  src/content/docs/dropins/all/extending.mdx
  src/content/docs/dropins/all/labeling.mdx
  src/content/docs/dropins/all/linking.mdx
  src/content/docs/dropins/cart/tutorials/add-messages-to-mini-cart.mdx
  src/content/docs/dropins/cart/tutorials/configure-cart-summary.mdx
  src/content/docs/dropins/checkout/containers/terms-and-conditions.mdx
  src/content/docs/dropins/user-account/sidebar.mdx
  src/content/docs/get-started/images/CreateStorefrontSteps.svg
  src/content/docs/get-started/images/SimpleCreateStorefrontSteps.svg
  src/content/docs/get-started/images/default-storefront.webp
  src/content/docs/get-started/images/initialize-content.webp
  src/content/docs/get-started/images/storefront-site-boilerplate.png
  src/content/docs/get-started/index.mdx
  src/content/docs/merchants/get-started/enrichment.mdx
  src/content/docs/merchants/get-started/experiments.mdx
  src/content/docs/merchants/get-started/multistore.mdx
  src/content/docs/merchants/get-started/terms-and-conditions.mdx
  src/content/docs/setup/analytics/instrumentation.mdx
  src/content/docs/setup/configuration/commerce-configuration.mdx
  src/content/docs/setup/configuration/gated-content.mdx
  src/content/docs/setup/discovery/architecture.mdx
  src/content/docs/setup/launch/index.mdx
  src/content/docs/videos/customize-cart-summary.mdx
Labels: documentation

#286 fix: update more based on review
  src/content/docs/get-started/index.mdx
Labels: documentation

#291 fix: change prod build reviewer
  .jenkins/deliver-build.groovy
Labels: maintenance

#293 fix: add header to table
  src/content/docs/dropins/product-details/containers/product-gallery.mdx
Labels: documentation

#297 USF-1971: Filterable changelog
  src/components/changelog/ChangelogEntry.astro
  src/components/changelog/ChangelogFilter.astro
  src/content/docs/releases/changelog.mdx
  src/content/docs/releases/index.mdx
  src/content/docs/setup/configuration/storefront-compatibility/v247.mdx
  src/content/docs/setup/configuration/storefront-compatibility/v248.mdx
  src/styles/custom.css
Labels: enhancement

#295 COMOPT-417, Product List Container Doc
  astro.config.mjs
  public/images/dropins/recommendations/product-list.png
  src/content/docs/dropins/recommendations/containers/product-list.mdx
Labels: documentation

#283 USF 1987 - Developer can enable updating product variations in the cart summary container
  astro.config.mjs
  src/content/docs/dropins/cart/tutorials/enable-product-variation-updates-in-cart.mdx
Labels: documentation
