Repository commerce-docs/microsite-commerce-storefront, pull requests merged in 2025-07, with the labels that each got.

#369 Add email address for Luma Bridge beta access
  src/content/docs/setup/discovery/luma-bridge.mdx
Labels: editorial

#370 add troubleshooting section specifically for vcl deletion issue
  src/content/docs/setup/configuration/content-delivery-network.mdx
Labels: major-update

#372 COMDOX-1267: Update .jenkins/deliver-build.groovy
  .jenkins/deliver-build.groovy
Labels: maintenance

#374 fix: add redirect for old localizing topic
  astro.config.mjs
Labels: bug, maintenance

#365 USF-2163: Further development of Storefront Builder content
  _drafts/_content-authoring.mdx
  astro.config.mjs
  public/images/merchants/LocalizationSteps.001.png
  src/components/PDFViewer.astro
  src/content/docs/index.mdx
  src/content/docs/merchants/images/placeholder.webp
  src/content/docs/merchants/multistore/content-localization.mdx
  src/content/docs/merchants/storefront-builder/_digital-assets-management.mdx
  src/content/docs/merchants/storefront-builder/content-commerce-blocks.mdx
  src/content/docs/merchants/storefront-builder/document-authoring.mdx
  src/content/docs/merchants/storefront-builder/images/storefront-builder.png
  src/content/docs/merchants/storefront-builder/index.mdx
  src/content/docs/merchants/storefront-builder/visual-editor.mdx
Labels: documentation

#378 remove beta badge
  astro.config.mjs
Labels: maintenance

#382 feat: add 'remove' function to slot documentation
  src/content/docs/dropins/all/slots.mdx
Labels: documentation

#383 USF 2382 - In cart flavor & size editing
  src/content/docs/dropins/cart/tutorials/enable-product-variation-updates-in-cart.mdx
Labels: major-update

#389 Remove unnecessary examples from product discover container docs.
  src/content/docs/dropins/product-discovery/containers/facets.mdx
  src/content/docs/dropins/product-discovery/containers/product-list.mdx
  src/content/docs/dropins/product-discovery/containers/results-info.mdx
  src/content/docs/dropins/product-discovery/containers/search-bar-input.mdx
  src/content/docs/dropins/product-discovery/containers/search-bar-results.mdx
Labels: technical
